#!/bin/bash
#default to a directory called source in your home
HOMESRC=~/source
DSTLINK=~/.local/bin

if [ ! -d "${HOMESRC}" ];then
  mkdir "${HOMESRC}"
  echo "Created a source directory in home for you. Change the variable at the top of the script if you want it located elsewhere"
fi

if [ -d "${HOMESRC}/lutris/.git" ];then
  cd "${HOMESRC}/lutris"
  git fetch
  git reset --hard HEAD
  git merge '@{u}'
else
  echo "Lutris not found - performing first clone"
  cd "${HOMESRC}"
  git clone https://github.com/lutris/lutris.git
fi
# link lutris binary to something in our path - user usually has .local/bin
rm -f "${DSTLINK}/lutris"
ln -s "${HOMESRC}/lutris/bin/lutris" "${DSTLINK}/lutris"

# Updated - found command to do this as a user. requires the installation of python3-venv
# old build used to: "sudo ./configure.sh --prefix=/usr"
if [ -d "${HOMESRC}/ULWGL-launcher/.git" ];then
  cd "${HOMESRC}/ULWGL-launcher"
  make clean
  rm -rf ${HOMESRC}/ULWGL-launcher/usr
  git fetch
  git reset --hard HEAD
  git merge '@{u}'
  ./configure.sh --user-install
  make
  make install
else
  echo "ULWGL not found - performing first clone"
  cd "${HOMESRC}"
  git clone https://github.com/Open-Wine-Components/ULWGL-launcher.git
  ./configure.sh --user-install
  make
  make install
fi
