#!/bin/bash
#default to a directory called source in your home
HOMESRC=~/source
DSTLINK=~/.local/bin

if [ ! -d "${HOMESRC}" ];then
  mkdir "${HOMESRC}"
  echo "Created a source directory in home for you. Change the variable at the top of the script if you want it located elsewhere"
fi

if [ -d "${HOMESRC}/lutris/.git" ];then
  cd "${HOMESRC}/lutris"
  git fetch
  git reset --hard HEAD
  git merge '@{u}'
else
  echo "Lutris not found - performing first clone"
  cd "${HOMESRC}"
  git clone https://github.com/lutris/lutris.git
fi
# link lutris binary to something in our path - user usually has .local/bin
rm -f "${DSTLINK}/lutris"
ln -s "${HOMESRC}/lutris/bin/lutris" "${DSTLINK}/lutris"

# Updated - found command to do this as a user. requires the installation of python3-venv
# Update2 - this moved to umu-launcher
# old build used to: "sudo ./configure.sh --prefix=/usr"
if [ -d "${HOMESRC}/umu-launcher/.git" ];then
  cd "${HOMESRC}/umu-launcher"
  make clean
  rm -rf ${HOMESRC}/umu-launcher/usr
  git fetch
  git reset --hard HEAD
  git merge '@{u}'
  ./configure.sh --user-install
  echo "Running make (quietly)"
  make 2>&1 >>/dev/null
  if [ $? -ne 0 ];then
    echo "Error running build - recommend checking manually, then run make install"
    exit 1
  fi
  make install
else
  echo "umu-launcher not found - performing first clone"
  cd "${HOMESRC}"
  git clone https://github.com/Open-Wine-Components/umu-launcher.git
  cd umu-launcher
  ./configure.sh --user-install
  echo "Running make (quietly)"
  make 2>&1 >>/dev/null
  if [ $? -ne 0 ];then
    echo "Error running build - recommend checking manually, then run make install"
    exit 1
  fi
  make install
fi

if [ `echo $PATH | grep $DSTLINK >/dev/null; echo $?` -ne 0 ];then
  echo "Warning: Link destination not found in PATH - might want to change DSTLINK in script"
fi
